"""> Adding constraint on menuitems table for on delete cascade

Revision ID: 36972d0f1238
Revises: a727957ded92
Create Date: 2022-10-20 08:57:15.311142

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision = '36972d0f1238'
down_revision = 'a727957ded92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
