"""> Column type and properties tweaked in MenuItems table

Revision ID: 6ae631b4cad7
Revises: c03baa326d1a
Create Date: 2022-10-16 10:03:00.099993

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision = '6ae631b4cad7'
down_revision = 'c03baa326d1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
