"""Changing the MenuItems.id field from default value to manual value using uuid4

Revision ID: a727957ded92
Revises: 81f15daaa73d
Create Date: 2022-10-16 13:10:24.831001

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision = 'a727957ded92'
down_revision = '81f15daaa73d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
