"""> Rating column in MenuItems is changed to nullable

Revision ID: c03baa326d1a
Revises: f45d4b78079e
Create Date: 2022-10-16 09:56:15.480015

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c03baa326d1a'
down_revision = 'f45d4b78079e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menuitems', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('menuitems', 'rating',
                    existing_type=postgresql.DOUBLE_PRECISION(precision=53),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menuitems', 'rating',
                    existing_type=postgresql.DOUBLE_PRECISION(precision=53),
                    nullable=False)
    op.alter_column('menuitems', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###
